---
title: "Marcus Ramalho's CV"
author: Marcus Ramalho
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1zPVICSel5EB9M6d8bhhpVpBk5kDIrX_u8HDScEa-oYg/edit?usp=sharing",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data)
```


```{r}
if(params$pdf_mode){
  cat("Veja meu currículo online https://nextmarte.github.io/curriculo/")
} else {
  cat("[<i class='fas fa-download'></i> Baixar versão PDF](https://raw.githubusercontent.com/nextmarte/curriculo/aac878d21c76dc0d2045b62a8ea0f24002ee56e0/cv.pdf)")
}
```

Contato {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```



Linguagens e ferramentas {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------


Feito com o pacote [**pagedown**](https://github.com/rstudio/pagedown). 

O código fonte está disponível em [on github.com/nstrayer/cv](https://github.com/nextmarte/curriculo).

Último update `r Sys.Date()`.



Main
================================================================================

Marcus Ramalho {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```

Experiência profissional {data-icon=suitcase}
--------------------------------------------------------------------------------


```{r}
CV %<>% print_section('industry_positions')
```


Educação {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```



Experiência Acadêmica {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('research_positions')
```


<!-- These breaks just force a new page so section doesnt get cut off -->
<br>
<br>
<br>

Experiência docente {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('teaching_positions')
```


<br>
<br>


Publicações e Palestras {data-icon=book}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('academic_articles')
```



```{r}
CV %<>% print_links()
```

